language: bash
jobs:
  include:
    - stage: init
      before_install:
      - date
      before_script:
      - date
      install:
      - sudo apt install jq
      script:
      - jq --version
    - stage: test
      script: jq --version
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: test
      script: ./wait.sh
    - stage: deploy
      script: echo deploy
